// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package portbpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type PortMonitorPortEvent struct {
	_        structs.HostLayout
	Pid      uint32
	Sport    uint16
	Family   uint16
	OldState int32
	NewState int32
}

// LoadPortMonitor returns the embedded CollectionSpec for PortMonitor.
func LoadPortMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PortMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load PortMonitor: %w", err)
	}

	return spec, err
}

// LoadPortMonitorObjects loads PortMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PortMonitorObjects
//	*PortMonitorPrograms
//	*PortMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPortMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPortMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PortMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PortMonitorSpecs struct {
	PortMonitorProgramSpecs
	PortMonitorMapSpecs
	PortMonitorVariableSpecs
}

// PortMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PortMonitorProgramSpecs struct {
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
}

// PortMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PortMonitorMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// PortMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PortMonitorVariableSpecs struct {
	UnusedPortEvent *ebpf.VariableSpec `ebpf:"unused_port_event"`
}

// PortMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPortMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type PortMonitorObjects struct {
	PortMonitorPrograms
	PortMonitorMaps
	PortMonitorVariables
}

func (o *PortMonitorObjects) Close() error {
	return _PortMonitorClose(
		&o.PortMonitorPrograms,
		&o.PortMonitorMaps,
	)
}

// PortMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPortMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type PortMonitorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *PortMonitorMaps) Close() error {
	return _PortMonitorClose(
		m.Events,
	)
}

// PortMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadPortMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type PortMonitorVariables struct {
	UnusedPortEvent *ebpf.Variable `ebpf:"unused_port_event"`
}

// PortMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPortMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type PortMonitorPrograms struct {
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
}

func (p *PortMonitorPrograms) Close() error {
	return _PortMonitorClose(
		p.TraceInetSockSetState,
	)
}

func _PortMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed portmonitor_arm64_bpfel.o
var _PortMonitorBytes []byte
